# Generated by Django 5.2 on 2025-08-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='aadhaar_front',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar/'),
        ),
    ]
